### ISSUE TITLE
Underscore in "osm_seattle.snowandsnow.us" causes problems to JOSM

### ISSUE THREAD

**Issue by don-vip** [cliffordsnow/cliffordsnow.github.io#1]
Hello,
This is an upstream bug report for https://josm.openstreetmap.de/ticket/15394.
Users of http://tasks.openstreetmap.us/project/118 are unable to download .osm files from https://cliffordsnow.github.io/CorpusChristi/483550018011004.osm if they run JOSM with WebStart because the download is redirected to http://osm_seattle.snowandsnow.us/CorpusChristi/483550020012004.osm, and in this mode, Java does not allow to have underscores in host names. Surprisingly, Java allows them when it is not launched via WebStart.

We cannot do anything in JOSM as it is a Java bug. I wonder if you could remove the underscore from the hostname, or replace it by a dash?

**Comment by cliffordsnow** [comment]
No - If I change the import url then the project needs to be re-created which would lose all of the areas already complete. Best advice I can give is to not use WebStart. In the future, I will avoid using Github. I was having AWS problems which I believe have been fixed.
